# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(tag)
    - task: ECRPushImage@1
      displayName: Push ECR latest
      inputs:
        awsCredentials: 'aws-connection'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'ufsmgo-api'
        repositoryName: ufsmgo-api
        pushTag: latest

    - task: ECRPushImage@1
      displayName: Push ECR latest
      inputs:
        awsCredentials: 'aws-connection'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'ufsmgo-api'
        repositoryName: ufsmgo-api
        pushTag: $(tag)