version: '3'

services:
  ufsmgo:
    #image: mrtrevisan/ufsmgo:latest

    build:
      context: .
      dockerfile: Dockerfile
    container_name: ufsmgo
    restart: always
    env_file: .env

    ports:
      - "3000:3000"
    #networks:
    #  - traefik-proxy

#networks:
#  traefik-proxy:
#    external: true