version: '3'

services:
  ufsmgo-api:
    #image: mrtrevisan/ufsmgo-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ufsmgo-api
    restart: always
    env_file: .env
    #environment:
    #  HOST_DB: $HOST_DB
    #ports:
    #  - "15432:5432"
    networks:
      - traefik-proxy
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-proxy"
        - "traefik.http.routers.ufsmgo-api.entrypoints=http"
        - "traefik.http.routers.ufsmgo-api.rule=Host(`ufsmgo-api.cloud.local`)"
        - "traefik.http.middlewares.ufsmgo-api-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.ufsmgo-api.middlewares=ufsmgo-api-https-redirect"
        - "traefik.http.routers.ufsmgo-api-secure.entrypoints=https"
        - "traefik.http.routers.ufsmgo-api-secure.rule=Host(`ufsmgo-api.cloud.local`)"
        - "traefik.http.routers.ufsmgo-api-secure.tls=true"
        #- "traefik.http.routers.ufsmgo-api-secure.tls.certresolver=http"
        - "traefik.http.services.ufsmgo-api-secure.loadbalancer.server.port=3000"

networks:
  traefik-proxy:
    external: true