//swagger
import swaggerAutogen from 'swagger-autogen'

const outputFile = './swagger.json'
const endpointsFiles = [
    '../controllers/authController.js', 
    '../controllers/dataController.js',
    '../controllers/userController.js', 
    '../middlewares/ensureNameNotUsed.ts', 
    '../middlewares/ensureUserExists.ts',
    '../server.js'
]

const swaggerOptions = {
    info: {
        title: 'ufsmgo-api',
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: 'ufsmgo-api.cloud.local'
};

swaggerAutogen(outputFile, endpointsFiles, swaggerOptions);