//swagger
import swaggerAutogen from 'swagger-autogen'

const outputFile = './swagger.json'
const endpointsFiles = ['../controllers/authController.mjs', '../controllers/dataController.mjs', '../controllers/userController.mjs']

const swaggerOptions = {
    info: {
        title: 'ufsmgo-api',
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
};

swaggerAutogen(outputFile, endpointsFiles, swaggerOptions);